### ISSUE TITLE
css file not linked properly

### ISSUE THREAD

**Issue by ec-daisuketanabe** [Leandermeanders/project#1]
In <head> section, the `style.css `file was linked as `<link rel="stylesheet" href="css/style.css">`, but as the `style.css` file is in the same folder as the other files, it should be changed to `<link rel="stylesheet" href="style.css">`

`css/style.css` means that `sytel.css` is inside the `css` folder, which is not the case for your project.

Can you update `<link>` in `<head>` and commit the project, and push the changes to GitHub?

**Comment by Leandermeanders** [comment]
Thanks dai yeah I will sort it out when finished my shift.
Leander mock

Sent from my iPhone

On 15 Aug 2023, at 14:59, ec-daisuketanabe ***@***.***> wrote:

﻿

In section, the style.css file was linked as <link rel="stylesheet" href="css/style.css">, but as the style.css file is in the same folder as the other files, it should be changed to <link rel="stylesheet" href="style.css">

css/style.css means that sytel.css is inside the css folder, which is not the case for your project.

Can you update <link> in <head> and commit the project, and push the changes to GitHub?
